import pytest

from src import iati_utilities


@pytest.mark.parametrize(
    "input,expected",
    [
        ("", False),
        ("String without an opening element", False),
        ("Contents with something before correct element <iati-activities>", False),
        ("Contents with something before correct element <iati-organisations>", False),
        ('<?xml version="1.0"?>String without an opening element', False),
        ('<?xml version="1.0"?>String without an opening element<iati-activities>', False),
        ("iati-activities more here", False),
        ("iati-activities> and more content", False),
        ("<iati activities", False),
        ("<iati activities something here", False),
        ("iati-organisations more here", False),
        ("iati-organisations> and more content", False),
        ("<iati organisations", False),
        ("<iati organisations something here", False),
        ("<iati organisations something here", False),
        ("<iati organisations something here", False),
    ],
)
def test_content_has_iati_opening_element_negatives(input, expected):
    assert iati_utilities.content_has_iati_opening_element(input) == expected


@pytest.mark.parametrize(
    "input,expected",
    [
        ("<iati-activities", True),
        ("<iati-activities and more content here", True),
        ("<iati-organisations", True),
        ("<iati-organisations and more content", True),
        ("   <iati-activities", True),
        ("	<iati-activities", True),  # tab
        ("   <iati-activities and more content here", True),
        ("   <iati-organisations", True),
        ("   <iati-organisations and more content", True),
        (
            """
                              <iati-activities and more content""",
            True,
        ),
        ("""<!-- comment --><iati-activities and more content""", True),
        ("""    <!-- comment --><iati-activities and more content""", True),
        ("""<!--  --><iati-activities and more content""", True),
        ("""<?xml version="1.0"?><!-- comment --><iati-activities and more content""", True),
        ("""<?xml version="1.0"?>  <!-- comment --><iati-activities and more content""", True),
        ("""<?xml version="1.0"?><!-- comment -->  <iati-activities and more content""", True),
        ("""<?xml version="1.0"?><!-- -->  <iati-activities and more content""", True),
        ("""<?xml version="1.0"?><!---->  <iati-activities and more content""", True),
        (
            """<?xml version="1.0"?><!--
                              comment here
                              -->  <iati-activities and more content""",
            True,
        ),
        (
            """<?xml version="1.0"?>
                <!--This file has been generated by a tool which inserts a really long comment
                before the first IATI element.  See https://example.com for more information on this tool. -->
                <iati-activities and more content""",
            True,
        ),
        (
            """<?xml version="1.0"?>
                <!--This file has two XML comments before the content. --> <!-- A second comment. -->
                <iati-activities and more content""",
            True,
        ),
    ],
)
def test_content_has_iati_opening_element_positives(input, expected):
    assert iati_utilities.content_has_iati_opening_element(input) == expected


def test_get_hash():
    small_activity_file = open("tests/artefacts/dataset-files/activity_file_01.xml", "rb").read()
    hash = iati_utilities.get_hash_of_bytes(small_activity_file)
    assert hash == "3486d4cee556d2584020bed2c86305465b8b3880"


def test_get_hash_excluding_generated_timestamp():
    small_activity_file = open("tests/artefacts/dataset-files/activity_file_01.xml", "r", encoding="utf-8").read()
    hash = iati_utilities.get_hash_excluding_generated_timestamp(small_activity_file, "utf-8")
    assert hash == "759eaa39276381f3fc146232cefd2111a2abc199"
