---
name: "Run linters: isort, black, flake8, mypy"

on:  # yamllint disable-line rule:truthy
  workflow_call:
  workflow_dispatch:
  push:
    branches:
      - '**'
      - '!develop'
      - '!main'

jobs:
  run-linters:
    name: Python Code Checking
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the Repository
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: 3.13

      - name: Install requirements
        run: pip install -r requirements-dev.txt

      - name: Linting with Isort
        run: isort . --check-only

      - name: Linting with Black
        run: black . --check

      - name: Linting with Flake8
        run: flake8

      - name: Type checking with MyPy
        run: mypy
